//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho

import UIKit

final class ___VARIABLE_moduleName___Interactor {

    // MARK: - Interactor setup -
    weak var viewModel: ___VARIABLE_moduleName___ViewModel?


}