//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho

import UIKit

final class ___VARIABLE_moduleName___Router {

    // MARK: - Router setup -
    weak var viewController: UIViewController?
    static func createModule() -> UIViewController {
        let view = ___VARIABLE_moduleName___ViewController(nibName: nil, bundle: nil)
        let interactor = ___VARIABLE_moduleName___Interactor()
        let router = ___VARIABLE_moduleName___Router()
        let viewModel = ___VARIABLE_moduleName___ViewModel(interactor: interactor)

        view.command = viewModel
        interactor.viewModel = viewModel
        router.viewController = view

        return view
    }

}