//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho

import UIKit

final class ___VARIABLE_moduleName___ViewModel {

    // MARK: - Private properties -
    private let interactor : ___VARIABLE_moduleName___Interactor


    init(interactor: ___VARIABLE_moduleName___Interactor) {
        self.interactor = interactor
    }

    // MARK: - Lifecycle -

  
}