//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho


import UIKit

final class ___VARIABLE_moduleName___ViewController: UIViewController {

    // MARK: - Public properties -
    var command: ___VARIABLE_moduleName___ViewModel?


    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}